import{mkdirSync,mkdtempSync,rmSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{afterEach,describe,expect,it,vi}from'vitest';import{AgentCompositionService,type VerifiedCreationCallerEvidence,type VerifiedTransactionConsumerEvidence}from'../src/agent-composition-service.js';
import{DurableAgentGenerationAuthority}from'../src/agent-generation-reservation.js';import{TempAgentPlanReservationRoot}from'../src/temp-agent-plan-reservation.js';
import{loadConfigResourceSnapshot}from'../src/config-resource-loader.js';import{computeBrainAdapterPolicyDigest,type BrainAdapterPolicy,type TrustedAdapterEnforcementBindings,type VerifiedAdapterEnforcementEvidence}from'../src/harness/brain-adapter.js';
import{computeBrainDigest,computePermissionsDigest}from'../src/agent-plan.js';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
function fixture(){const root=mkdtempSync(join(tmpdir(),'temp-reservation-'));roots.push(root);mkdirSync(join(root,'fleet.conf.d','roles.d'),{recursive:true});writeFileSync(join(root,'fleet.yaml'),'schema_version: 2\nconfig_dir: fleet.conf.d\npolicy: {}\n');writeFileSync(join(root,'fleet.conf.d','roles.d','r.yaml'),'kind: Role\nversion: 1\nid: R\nspec:\n  mission: Test\n');
  const snapshot=loadConfigResourceSnapshot({bootstrapFile:join(root,'fleet.yaml')}),caller={}as VerifiedCreationCallerEvidence,tx={}as VerifiedTransactionConsumerEvidence,evidence={}as VerifiedAdapterEnforcementEvidence;
  const brain={harness:'codex',model:'gpt-test',effort:'high',session:'acp'}as const,permissions={approval:'ask',filesystem:'workspace',unattended:'deny'}as const;
  const policyValue:BrainAdapterPolicy={schemaVersion:1,kind:'codex_acp',adapterVersion:'1.1.7',modelPolicy:{schemaVersion:1,kind:'syntax_only',revision:'x'},launch:{kind:'bundled'}};const policy={revision:'p',digest:computeBrainAdapterPolicyDigest('p',policyValue),value:policyValue};
  const trusted:TrustedAdapterEnforcementBindings={harness:'codex',session:'acp',adapterId:'codex-acp',adapterVersion:'1.1.7',policyDigest:policy.digest,brainDigest:computeBrainDigest(brain),permissionsDigest:computePermissionsDigest(permissions),launch:{kind:'bundled',packageName:'@agentclientprotocol/codex-acp',manifestPath:'/m',entrypointPath:'/e',version:'1.1.7',identity:{manifest:{path:'/m',dev:'1',ino:'1',size:1,mtimeNs:'1',sha256:`sha256:${'1'.repeat(64)}`},entrypoint:{path:'/e',dev:'1',ino:'2',size:1,mtimeNs:'1',sha256:`sha256:${'2'.repeat(64)}`}}},enforcement:{approval:'native_adapter',filesystem:'native_adapter',unattended:'body_controller'}};
  const context=Object.freeze({principal:Object.freeze({id:'system',kind:'system' as const}),operation:Object.freeze({id:'x',type:'agent.create',resourceScope:'agents/a'}),authorizationRevision:'auth',snapshot,snapshotRevision:'graph',issuedAt:1});
  const service=new AgentCompositionService({authenticateContext:v=>v===caller?context:undefined,allocateGeneration:()=>Object.freeze({agentId:'a',generation:1,operationId:'x',authorizationRevision:'auth',snapshotDigest:snapshot.digest,snapshotRevision:'graph'}),authenticateTransactionConsumer:v=>v===tx},{resolvePolicy:()=>({policy,enforcementEvidence:evidence})},{authenticateAdapterEvidence:v=>v===evidence?trusted:undefined},()=>2);
  const generations=new DurableAgentGenerationAuthority(join(root,'trusted'));const reservation=new TempAgentPlanReservationRoot(service,service.issueTransactionConsumer(tx),generations);const request={callerEvidence:caller,source:{kind:'runtime_composition' as const,agentId:'a',role:'R',identity:{name:'a',ownership:'create_temporary' as const},lifecycle:'temporary' as const,brain,permissions}};return{reservation,generations,request};}
describe('TempAgentPlanReservationRoot',()=>{
  it.each([['lifecycle','persistent'],['ownership','existing'],['action','other']]as const)('rejects %s mismatch before persistence',async(kind,value)=>{const f=fixture();const request=kind==='lifecycle'?{...f.request,source:{...f.request.source,lifecycle:value as'persistent'}}:kind==='ownership'?{...f.request,source:{...f.request.source,identity:{name:'a',ownership:value as'existing'}}}:f.request;await expect(f.reservation.reserve(request as never,kind==='action'?value:'x')).rejects.toThrow();expect(await f.generations.lookup('a','x')).toBeUndefined();});
  it('issues only same-instance opaque evidence and persists exact durable generation',async()=>{const f=fixture();const evidence=await f.reservation.reserve(f.request,'x');expect(f.reservation.authenticate(evidence)).toMatchObject({record:{agentId:'a',actionId:'x',generation:1}});expect(f.reservation.authenticate({...evidence}as never)).toBeUndefined();expect(f.reservation.authenticate({}as never)).toBeUndefined();expect(await f.generations.lookup('a','x')).toBeDefined();});
  it('fails closed on foreign transaction consumer without durable state',async()=>{const f=fixture();const bad=new TempAgentPlanReservationRoot((f.reservation as never).composition,{}as never,f.generations);await expect(bad.reserve(f.request,'x')).rejects.toThrow();});
});
